// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api.ts";
import * as $2 from "./routes/auth.ts";
import * as $3 from "./routes/dashboard.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/list.tsx";
import * as $6 from "./routes/login.tsx";
import * as $7 from "./routes/movie/add.ts";
import * as $8 from "./routes/search.tsx";
import * as $9 from "./routes/theater/add.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api.ts": $1,
    "./routes/auth.ts": $2,
    "./routes/dashboard.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/list.tsx": $5,
    "./routes/login.tsx": $6,
    "./routes/movie/add.ts": $7,
    "./routes/search.tsx": $8,
    "./routes/theater/add.ts": $9,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
