// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $auth from "./routes/auth.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $list from "./routes/list.tsx";
import * as $login from "./routes/login.tsx";
import * as $movie_add from "./routes/movie/add.ts";
import * as $search from "./routes/search.tsx";
import * as $theater_add from "./routes/theater/add.ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/auth.ts": $auth,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/list.tsx": $list,
    "./routes/login.tsx": $login,
    "./routes/movie/add.ts": $movie_add,
    "./routes/search.tsx": $search,
    "./routes/theater/add.ts": $theater_add,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
